version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=employee
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgresql://root:admin@postgres:5432/employee?sslmode=disable
      - GIN_MODE=release
    depends_on: 
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432","--","/app/start.sh"]
    command: ["/app/main"]

