// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Department struct {
	DepartmentID   int64  `json:"department_id"`
	DepartmentName string `json:"department_name"`
}

type Employee struct {
	EmployeeID   int64          `json:"employee_id"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	HireDate     time.Time      `json:"hire_date"`
	JobID        int64          `json:"job_id"`
	Salary       int64          `json:"salary"`
	ManagerID    sql.NullInt64  `json:"manager_id"`
	DepartmentID int64          `json:"department_id"`
}

type Job struct {
	JobID     int64         `json:"job_id"`
	JobTitle  string        `json:"job_title"`
	MinSalary sql.NullInt64 `json:"min_salary"`
	MaxSalary sql.NullInt64 `json:"max_salary"`
}
